name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "rajatkumarchahar@gmail.com"
          git config --global user.name "froxtrost"
          cd _site
          git init
          git add .
          git commit -m "Deploy Jekyll site to GitHub Pages"
          git push --force --quiet "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
